### ISSUE TITLE
Server keep crashing

### ISSUE THREAD

**Issue by cj-chua** [lnbits/lnbits-legend#399]
I run a lnbits server and it crashes on me randomly. I couldn't figure out what was causing the crash this time - any help would be appreciated. Here's the logs

```
 49 [2021-10-30 08:22:12,259] 62.171.190.75:48390 POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo 2 500 541 4040
 50 Traceback (most recent call last):
 51  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
 52    result = await self.dispatch_request(request_context)
 53  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart/app.py", line 1927, in dispatch_request
 54    raise request_.routing_exception
 55 quart.exceptions.NotFound: NotFound(404)
 56 Traceback (most recent call last):
 57  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
 58    result = await self.dispatch_request(request_context)
 59  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart/app.py", line 1927, in dispatch_request
 60    raise request_.routing_exception
 61 quart.exceptions.NotFound: NotFound(404)
 62 Traceback (most recent call last):
 63  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
 64    result = await self.dispatch_request(request_context)
 65  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart/app.py", line 1927, in dispatch_request
 66    raise request_.routing_exception
 67  quart.exceptions.MethodNotAllowed: MethodNotAllowed(405)
68Traceback (most recent call last):
 69  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
 70    result = await self.dispatch_request(request_context)
 71  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart/app.py", line 1927, in dispatch_request
 72    raise request_.routing_exception
 73quart.exceptions.MethodNotAllowed: MethodNotAllowed(405)
 74Traceback (most recent call last):
 75  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
 76    result = await self.dispatch_request(request_context)
 77  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart/app.py", line 1927, in dispatch_request
 78    raise request_.routing_exception
 79 quart.exceptions.NotFound: NotFound(404)
 80 Traceback (most recent call last):
 81  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
 82    "__main__", mod_spec)
 83  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
 84    exec(code, run_globals)
 85  File "/app/lnbits/__main__.py", line 33, in <module>
 86    app.run(host=app.config["HOST"], port=app.config["PORT"])
 87  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/quart_trio/app.py", line 68, in run
 88    trio.run(self.run_task, host, port, debug, use_reloader, ca_certs, certfile, keyfile)
 89  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/trio/_core/_run.py", line 1896, in run
 90    raise runner.main_task_outcome.error
 91  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/hypercorn/trio/__init__.py", line 42, in serve
 92    await worker_serve(app, config, shutdown_trigger=shutdown_trigger, task_status=task_status)
 93  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/hypercorn/trio/run.py", line 99, in worker_serve
 94    lifespan_nursery.cancel_scope.cancel()
 95  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/trio/_core/_run.py", line 741, in __aexit__
 96    raise combined_error_from_nursery
 97  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/trio/_highlevel_serve_listeners.py", line 25, in _run_handler
 98    await handler(stream)
 99  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/hypercorn/trio/tcp_server.py", line 77, in run
100    await self._read_data()
101  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/hypercorn/trio/tcp_server.py", line 110, in _read_data
102    await self.protocol.handle(RawData(data))
103  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/hypercorn/protocol/__init__.py", line 60, in handle
104    return await self.protocol.handle(event)
105  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/hypercorn/protocol/h2.py", line 183, in handle
106    await self._handle_events(events)
107  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/hypercorn/protocol/h2.py", line 230, in _handle_events
108    await self.streams[event.stream_id].handle(
109KeyError: 1
```

**Comment by arcbtc** [comment]
Run the latest version, which uses FastAPI instead of Quart and is far more stable
