### ISSUE TITLE
User Manager API Issues

### ISSUE THREAD

**Issue by bstin** [lnbits/lnbits-legend#441]
I'm running LNBits as part of Umbrel 0.4.9 and I can't get any of the "User Manager API" endpoints to work without throwing an error. 

For example:

```
$ curl -X GET http://192.168.1.60:3007/usermanager/usermanager/api/v1/users -H "X-Api-Key: REDACTED"
LNbits internal error!

Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 1927, in dispatch_request
    raise request_.routing_exception
quart.exceptions.NotFound: NotFound(404)


If you believe this shouldn't be an error please bring it up on https://t.me/lnbits%
```

The other API (non User Manager) works fine. 

```
$ curl http://192.168.1.60:3007/api/v1/wallet -H "X-Api-Key: REDACTED"                              
{
  "balance": 10100, 
  "id": "REDACTED", 
  "name": "User1"
}
```

Any ideas?

**Comment by callebtc** [comment]
This is fortunately just a stupid error on the documentation. See the endpoint, "usermanager" is printed twice.
