### ISSUE TITLE
Blank screen for Wallet operations

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits-legend#490]
Having installed the Legend version (using both sets of install instructions) the home page appears:

![image](https://user-images.githubusercontent.com/388061/149203794-84dfba91-1ff6-4ee0-88e1-0fe87263f696.png)

After naming the user though, the screen is blank (despite appears to be normal HTML when view-source is used)

```
Starting LNbits with
  - git version: a00e46f629696e054321ce03fa1c91b3a2fe832f
  - site title: LNbits LEGEND
  - debug: True
  - data folder: ./data
  - funding source: LNbitsWallet
  - service fee: 0.0

INFO:     Started server process [31474]
INFO:     Waiting for application startup.
  ✔️ LNbitsWallet seems to be connected and with a balance of 9468007 msat.
INFO:     Application startup complete.
  ✔️ All migrations done.
INFO:     192.168.1.159:0 - "GET / HTTP/1.0" 200 OK
INFO:     192.168.1.159:0 - "GET /core/static/js/index.js HTTP/1.0" 200 OK
INFO:     192.168.1.159:0 - "GET /favicon.ico HTTP/1.0" 200 OK
INFO:     192.168.1.159:0 - "GET /wallet?usr=290e91f96d2f45a2973ddf307c7991df&wal=41769b4263404bdc935eedef836bfcab HTTP/1.0" 200 OK
INFO:     192.168.1.159:0 - "GET /core/static/js/wallet.js HTTP/1.0" 304 Not Modified
INFO:     192.168.1.159:0 - "GET /wallet?usr=290e91f96d2f45a2973ddf307c7991df&wal=41769b4263404bdc935eedef836bfcab HTTP/1.0" 200 OK
INFO:     192.168.1.159:0 - "GET /core/static/js/wallet.js HTTP/1.0" 200 OK
INFO:     192.168.1.159:0 - "GET /favicon.ico HTTP/1.0" 200 OK
```

**Comment by HamishMacEwan** [comment]
Installed LNbits-legend on a different host:

`Linux merak-4 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux`

And it worked!  

Currently the problem of blank screen after home page occurs on:

`Linux myNode 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux`

**Comment by HamishMacEwan** [comment]
I checked the Dev tools console in Google Chrome for both sites and found from the working version:

```
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:9064 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
DevTools failed to load source map: Could not load content for chrome-extension://iplppiggblloelhoglpmkmbinggcaaoc/app/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

The failing blank page version had some similarities, but differences too, that look significant:
```
vue.js:634 [Vue warn]: Error in data(): "TypeError: Cannot read properties of undefined (reading 'map')"

(found in <Root>)
warn @ vue.js:634
vue.js:1897 TypeError: Cannot read properties of undefined (reading 'map')
    at Object.user (base.js:141:10)
    at Vue.data (wallet.js:114:24)
    at Vue.mergedInstanceDataFn (vue.js:1240:22)
    at getData (vue.js:4745:19)
    at initData (vue.js:4702:9)
    at initState (vue.js:4641:7)
    at Vue._init (vue.js:5000:7)
    at new Vue (vue.js:5078:10)
    at wallet.js:109:1
logError @ vue.js:1897
vue.js:634 [Vue warn]: Error in created hook: "TypeError: Cannot set properties of undefined (setting 'allowedThemes')"

(found in <Root>)
warn @ vue.js:634
vue.js:1897 TypeError: Cannot set properties of undefined (setting 'allowedThemes')
    at Vue.created (base.js:340:26)
    at invokeWithErrorHandling (vue.js:1863:59)
    at callHook (vue.js:4220:9)
    at Vue._init (vue.js:5002:7)
    at new Vue (vue.js:5078:10)
    at wallet.js:109:1
logError @ vue.js:1897
vue.js:634 [Vue warn]: Error in created hook: "TypeError: Cannot read properties of undefined (reading 'wallet')"

(found in <Root>)
warn @ vue.js:634
vue.js:1897 TypeError: Cannot read properties of undefined (reading 'wallet')
    at Vue.fetchBalance (wallet.js:633:35)
    at Vue.created (wallet.js:651:10)
    at invokeWithErrorHandling (vue.js:1863:59)
    at callHook (vue.js:4220:9)
    at Vue._init (vue.js:5002:7)
    at new Vue (vue.js:5078:10)
    at wallet.js:109:1
logError @ vue.js:1897
vue.js:634 [Vue warn]: Property or method "g" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.js:634
vue.js:634 [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'allowedThemes')"

(found in <Root>)
warn @ vue.js:634
vue.js:1897 TypeError: Cannot read properties of undefined (reading 'allowedThemes')
    at Proxy.eval (eval at createFunction (vue.js:11649:14), <anonymous>:3:760)
    at Vue._render (vue.js:3551:24)
    at Vue.updateComponent (vue.js:4067:23)
    at Watcher.get (vue.js:4478:27)
    at new Watcher (vue.js:4467:14)
    at mountComponent (vue.js:4074:5)
    at Vue.$mount (vue.js:9044:12)
    at Vue.$mount (vue.js:11944:18)
    at Vue._init (vue.js:5012:12)
    at new Vue (vue.js:5078:10)
logError @ vue.js:1897
vue.js:634 [Vue warn]: Error in mounted hook: "TypeError: Cannot read properties of undefined (reading 'wallet')"

(found in <Root>)
warn @ vue.js:634
vue.js:1897 TypeError: Cannot read properties of undefined (reading 'wallet')
    at Vue.mounted (wallet.js:674:40)
    at invokeWithErrorHandling (vue.js:1863:59)
    at callHook (vue.js:4220:9)
    at mountComponent (vue.js:4087:7)
    at Vue.$mount (vue.js:9044:12)
    at Vue.$mount (vue.js:11944:18)
    at Vue._init (vue.js:5012:12)
    at new Vue (vue.js:5078:10)
    at wallet.js:109:1
logError @ vue.js:1897
vue.js:9055 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:9064 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
DevTools failed to load source map: Could not load content for chrome-extension://iplppiggblloelhoglpmkmbinggcaaoc/app/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by arcbtc** [comment]
Excelllent bug reporting!
Its likely your browser caching the wallet.js, as in a few updates we had to change some things. You can use incognito, delete cookies, or wait a bit and the cache shold update
