### ISSUE TITLE
LNDHub Error with Zeus Wallet

### ISSUE THREAD

**Issue by rasodu** [lnbits/lnbits-legend#666]
I have enabled LndHub extension and connected it to my Zeus Wallet.
I am getting below error message when I try to connect.

```
lnbits-testnet_1     | INFO:     172.19.0.1:34468 - "POST /lndhub/ext/auth?type=auth HTTP/1.1" 200 OK
lnbits-testnet_1     | handled error Traceback (most recent call last):
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, _send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 18, in __call__
lnbits-testnet_1     |     await responder(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 35, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, self.send_with_gzip)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
lnbits-testnet_1     |     raise exc from None
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, sender)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
lnbits-testnet_1     |     await route.handle(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
lnbits-testnet_1     |     await self.app(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
lnbits-testnet_1     |     response = await func(request)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
lnbits-testnet_1     |     dependant=dependant, values=values, is_coroutine=is_coroutine
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
lnbits-testnet_1     |     return await dependant.call(**values)
lnbits-testnet_1     |   File "./lnbits/extensions/lndhub/views_api.py", line 115, in lndhub_balance
lnbits-testnet_1     |     return {"BTC": {"AvailableBalance": wallet.wallet.balance}}
lnbits-testnet_1     | AttributeError: 'NoneType' object has no attribute 'balance'
lnbits-testnet_1     | 
lnbits-testnet_1     | INFO:     172.19.0.1:34468 - "GET /lndhub/ext/balance HTTP/1.1" 200 OK
lnbits-testnet_1     | Traceback (most recent call last):
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, _send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 18, in __call__
lnbits-testnet_1     |     await responder(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 35, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, self.send_with_gzip)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
lnbits-testnet_1     |     raise exc from None
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, sender)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
lnbits-testnet_1     |     await route.handle(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
lnbits-testnet_1     |     await self.app(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
lnbits-testnet_1     |     response = await func(request)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
lnbits-testnet_1     |     dependant=dependant, values=values, is_coroutine=is_coroutine
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
lnbits-testnet_1     |     return await dependant.call(**values)
lnbits-testnet_1     |   File "./lnbits/extensions/lndhub/views_api.py", line 115, in lndhub_balance
lnbits-testnet_1     |     return {"BTC": {"AvailableBalance": wallet.wallet.balance}}
lnbits-testnet_1     | AttributeError: 'NoneType' object has no attribute 'balance'
lnbits-testnet_1     | ERROR:    Exception in ASGI application
lnbits-testnet_1     | Traceback (most recent call last):
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
lnbits-testnet_1     |     result = await app(self.scope, self.receive, self.send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
lnbits-testnet_1     |     return await self.app(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
lnbits-testnet_1     |     await super().__call__(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
lnbits-testnet_1     |     await self.middleware_stack(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
lnbits-testnet_1     |     raise exc from None
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, _send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 18, in __call__
lnbits-testnet_1     |     await responder(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 35, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, self.send_with_gzip)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
lnbits-testnet_1     |     raise exc from None
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
lnbits-testnet_1     |     await self.app(scope, receive, sender)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
lnbits-testnet_1     |     await route.handle(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
lnbits-testnet_1     |     await self.app(scope, receive, send)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
lnbits-testnet_1     |     response = await func(request)
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
lnbits-testnet_1     |     dependant=dependant, values=values, is_coroutine=is_coroutine
lnbits-testnet_1     |   File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
lnbits-testnet_1     |     return await dependant.call(**values)
lnbits-testnet_1     |   File "./lnbits/extensions/lndhub/views_api.py", line 115, in lndhub_balance
lnbits-testnet_1     |     return {"BTC": {"AvailableBalance": wallet.wallet.balance}}
lnbits-testnet_1     | AttributeError: 'NoneType' object has no attribute 'balance'
lnbits-testnet_1     | INFO:     172.19.0.1:34728 - "GET /lndhub/ext/getuserinvoices?limit=200 HTTP/1.1" 200 OK
```

**Comment by rasodu** [comment]
@[petrkr](https://github.com/petrkr), can you tell if it's LnBits issue or Zeus wallet issue?

**Comment by callebtc** [comment]
Looks to me like you're accessing a wallet that does not exist in LNbits. Are you sure it does?

**Comment by rasodu** [comment]
Yes, the wallet exists. I am scanning LndHub QR code in Zeus wallet.
I was using version 0.8.0 of docker image. I have created new image from the repository and look like it's not giving error.
I will track the issue for a few more days and open the issue if I see it.
Thanks @callebtc
