### ISSUE TITLE
migration test error

### ISSUE THREAD

**Issue by dni** [lnbits/lnbits-legend#840]
i think something broke? it errors inside the `run migration`  but the test still passes

this needs some more investigation.

https://github.com/lnbits/lnbits-legend/runs/7667461103?check_suite_focus=true#step:7:61

```
 2022-08-04 07:43:24.94 | ERROR | Traceback (most recent call last):
  File "/home/runner/work/lnbits-legend/lnbits-legend/lnbits/tasks.py", line 36, in catch_everything_and_restart
    await func()
  File "/home/runner/work/lnbits-legend/lnbits-legend/lnbits/tasks.py", line 97, in check_pending_payments
    await payment.check_pending()
  File "/home/runner/work/lnbits-legend/lnbits-legend/lnbits/core/models.py", line 147, in check_pending
    status = await WALLET.get_invoice_status(self.checking_id)
  File "/home/runner/work/lnbits-legend/lnbits-legend/lnbits/wallets/void.py", line 34, in get_invoice_status
    raise Unsupported("")
lnbits.wallets.base.Unsupported
```

**Comment by callebtc** [comment]
Fixed.
