### ISSUE TITLE
ERROR during `DELETE /lnurlp/api/v1/links/xxx`

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits-legend#872]
```sh
2022-08-13 13:28:18.04 | INFO | 185.220.101.33:0 - "DELETE /lnurlp/api/v1/links/xxxx HTTP/1.1" 204
2022-08-13 13:28:18.04 | ERROR | lnbits.app:basic_error:194 | handled error
2022-08-13 13:28:18.04 | ERROR | lnbits.app:basic_error:195 | ERROR:
Traceback (most recent call last):
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/lnbits-legend/lnbits/extensions/lnurlp/views_api.py", line 139, in api_link_delete
    raise HTTPException(status_code=HTTPStatus.NO_CONTENT)
starlette.exceptions.HTTPException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 104, in __call__
    await response(scope, receive, sender)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/responses.py", line 162, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 79, in sender
    await send(message)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/cors.py", line 153, in send
    await send(message)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 58, in send_with_gzip
    await self.send(message)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 533, in send
    raise RuntimeError("Response content longer than Content-Length")
RuntimeError: Response content longer than Content-Length
2022-08-13 13:28:18.04 | ERROR | Exception in ASGI application
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/lnbits-legend/lnbits/extensions/lnurlp/views_api.py", line 139, in api_link_delete
    raise HTTPException(status_code=HTTPStatus.NO_CONTENT)
starlette.exceptions.HTTPException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 104, in __call__
    await response(scope, receive, sender)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/responses.py", line 162, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 79, in sender
    await send(message)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/cors.py", line 153, in send
    await send(message)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 58, in send_with_gzip
    await self.send(message)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 533, in send
    raise RuntimeError("Response content longer than Content-Length")
RuntimeError: Response content longer than Content-Length
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 174, in __call__
    response = await self.handler(request, exc)
  File "/lnbits-legend/lnbits/app.py", line 205, in basic_error
    return JSONResponse(
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/starlette/responses.py", line 190, in render
    return json.dumps(
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.8/lib/python3.8/site-packages/pyln/client/lightning.py", line 13, in _patched_default
    return getattr(obj.__class__, "to_json", _patched_default.default)(obj)
TypeError: default() missing 1 required positional argument: 'o'
```

**Comment by leesalminen** [comment]
Fix for issue in PR #877
